/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AntDesignLeftOutlined: typeof import('~icons/ant-design/left-outlined')['default']
    AntDesignRightOutlined: typeof import('~icons/ant-design/right-outlined')['default']
    AntDesignUpOutlined: typeof import('~icons/ant-design/up-outlined')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NotImplemented: typeof import('./src/components/NotImplemented.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
  }
}
