// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
}

export { }
